--/ What is the total hours flown by each pilot?

SELECT
    cf.emp_num,
    SUM(cf.tot_char_hours) AS "Total Hours Flown"
FROM
         dw.charter_fact cf
    JOIN dw.pilot pd ON pd.emp_num = cf.emp_num
GROUP BY
    cf.emp_num
ORDER BY
    cf.emp_num;
    
--/ Display the total hours flown by each pilot in a descending order.

SELECT
    cf.emp_num,
    SUM(cf.tot_char_hours) AS "Total Hours Flown"
FROM
         dw.charter_fact cf
    JOIN dw.pilot pd ON pd.emp_num = cf.emp_num
GROUP BY
    cf.emp_num
ORDER BY
    "Total Hours Flown" DESC;
    
--/ What is the total hours flown by each category of pilot license?

SELECT
    pd.pil_license,
    SUM(cf.tot_char_hours) AS "Total Hours Flown"
FROM
         dw.charter_fact cf
    JOIN dw.pilot pd ON pd.emp_num = cf.emp_num
GROUP BY
    pd.pil_license
ORDER BY
    pd.pil_license;
    
--/ What is the total revenue generated by each pilot? Sort the results based on the Pilot ID.

SELECT
    cf.emp_num,
    SUM(cf.revenue) AS "Total Revenue"
FROM
         dw.charter_fact cf
    JOIN dw.pilot pd ON pd.emp_num = cf.emp_num
GROUP BY
    cf.emp_num
ORDER BY
    cf.emp_num;

--/ What is the total fuel consumption of the aircrafts manufactured by each manufacturer?

SELECT
    cf.mod_code,
    SUM(cf.tot_fuel) AS "Total Fuel Usage"
FROM
    dw.charter_fact cf
GROUP BY
    cf.mod_code;

--/ What is the total revenue generated in each year?

SELECT
    td.time_year,
    SUM(cf.revenue) AS "Total Revenue"
FROM
         dw.charter_fact cf
    JOIN dw.time td ON td.time_id = cf.time_id
GROUP BY
    td.time_year
ORDER BY
    td.time_year;
    
--/ What is the total fuel used from Oct to Dec 1995 by commercial pilots and airplane model C-90A. Sort the results by the month. How many rows of records do you get?

SELECT
    td.time_month,
    SUM(cf.tot_fuel) AS "Total Fuel Used"
FROM
         dw.charter_fact cf
    JOIN dw.pilot    pd ON pd.emp_num = cf.emp_num
    JOIN dw.model    md ON md.mod_code = cf.mod_code
    JOIN dw.time     td ON td.time_id = cf.time_id
WHERE
        upper(pd.pil_license) = 'COM'
    AND md.mod_code = 'C-90A'
    AND td.time_year = 1995
    AND td.time_month BETWEEN 10 AND 12
GROUP BY
    td.time_month
ORDER BY
    td.time_month;